# These are supported funding model platforms

#github: [ybhuxiao, gongmang1]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., 
custom: ['http://wowdata.top']# Replace with up to 4 custom sponsorship URLs e.g., 
